# Generated by Django 5.2.13 on 2026-04-16 00:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Provider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('website', models.URLField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='LLMModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('context_window', models.IntegerField()),
                ('input_price_per_1m', models.DecimalField(decimal_places=4, max_digits=10)),
                ('output_price_per_1m', models.DecimalField(decimal_places=4, max_digits=10)),
                ('arena_elo_score', models.IntegerField(blank=True, null=True)),
                ('release_date', models.DateField()),
                ('is_open_source', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('provider', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='models', to='app.provider')),
            ],
            options={
                'ordering': ['-arena_elo_score'],
                'unique_together': {('provider', 'name')},
            },
        ),
    ]
